from __future__ import annotations

from agent_platform_api.registries.prompt_persona_store.types import TemplateKind

GENERATED_MODULE_DOC = "Auto-generated by ADE Prompt Center."

DEFAULT_PROMPT_META: dict[str, dict[str, str]] = {
    "chat_v20260418": {
        "label": "Chat V20260418",
        "description": "Chat scenario prompt baseline for memory-augmented user conversations.",
    },
    "chat_v20260516": {
        "label": "Chat V20260516",
        "description": "Chat scenario prompt baseline with stricter user-memory update guidance.",
    },
    "comment_v20260418": {
        "label": "Comment V20260418",
        "description": "Comment scenario prompt baseline for stateless news and thread responses.",
    },
    "label_generic_entities_v1": {
        "label": "Label Generic Entities V1",
        "description": "Generic extraction baseline that returns grouped entity lists in JSON.",
    },
    "label_football_entities_v1": {
        "label": "Label Football Entities V1",
        "description": "Football article extraction example for player and team lists.",
    },
}

def default_meta_for_kind(kind: TemplateKind, key: str) -> dict[str, str]:
    defaults = DEFAULT_PROMPT_META if kind == "prompt" else {}
    if key in defaults:
        return dict(defaults[key])
    pretty = key.replace("-", " ").replace("_", " ").title()
    return {
        "label": pretty,
        "description": "",
    }
