"""
Auto-generated by ADE Prompt Center.
"""

LABEL = "Label Football Entities V1"
DESCRIPTION = "Football article labeling example for TEAM and PLAYER spans."
OUTPUT_SCHEMA = "{\"type\":\"object\",\"properties\":{\"spans\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"object\",\"properties\":{\"label\":{\"type\":\"string\"},\"text\":{\"type\":\"string\"},\"start\":{\"type\":\"integer\"},\"end\":{\"type\":\"integer\"}},\"required\":[\"label\",\"text\",\"start\",\"end\"],\"additionalProperties\":false}}},\"required\":[\"spans\"],\"additionalProperties\":false}"
PROMPT = """Extract PLAYER and TEAM spans. Return JSON only."""
