"""
Auto-generated by ADE Prompt Center.
"""

LABEL = "Label Generic Spans V1"
DESCRIPTION = "Generic span-labeling baseline that returns exact offsets in JSON."
OUTPUT_SCHEMA = "{\"type\":\"object\",\"properties\":{\"spans\":{\"type\":\"array\",\"maxItems\":64,\"items\":{\"type\":\"object\",\"properties\":{\"label\":{\"type\":\"string\"},\"text\":{\"type\":\"string\"},\"start\":{\"type\":\"integer\"},\"end\":{\"type\":\"integer\"}},\"required\":[\"label\",\"text\",\"start\",\"end\"],\"additionalProperties\":false}}},\"required\":[\"spans\"],\"additionalProperties\":false}"
PROMPT = """Extract PERSON, ORGANIZATION, LOCATION, DATE, and EVENT spans. Return JSON only."""
