from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


_KEY_PATTERN = re.compile(r"^[a-z][a-z0-9_-]{1,63}$")
_GENERATED_DOC = "Auto-generated by ADE Schema Center."
DEFAULT_LABEL_SCHEMA_KEY = "label_span_annotations_v1"


class LabelSchemaRegistryError(ValueError):
    """Raised when label schema registry operations fail."""


def default_label_span_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "spans": {
                "type": "array",
                "maxItems": 64,
                "items": {
                    "type": "object",
                    "properties": {
                        "label": {"type": "string", "minLength": 1},
                        "text": {"type": "string", "minLength": 1},
                        "start": {"type": "integer", "minimum": 0},
                        "end": {"type": "integer", "minimum": 0},
                    },
                    "required": ["label", "text", "start", "end"],
                    "additionalProperties": False,
                },
            }
        },
        "required": ["spans"],
        "additionalProperties": False,
    }


class LabelSchemaRegistry:
    """File-backed registry for Label Lab JSON output schemas."""

    def __init__(self, project_root: Path):
        self.project_root = Path(project_root).resolve()
        self.schema_dir = self.project_root / "schemas" / "label"
        self.archive_dir = self.schema_dir / "archive"
        self.schema_dir.mkdir(parents=True, exist_ok=True)
        self.archive_dir.mkdir(parents=True, exist_ok=True)

    def list_schemas(self, include_archived: bool = False) -> list[dict[str, Any]]:
        records = self._list_from_dir(self.schema_dir, archived=False)
        if include_archived:
            records.extend(self._list_from_dir(self.archive_dir, archived=True))
        records.sort(key=lambda item: (bool(item.get("archived")), str(item.get("key", ""))))
        return records

    def get_schema(self, key: str, *, archived: bool = False) -> dict[str, Any] | None:
        normalized = self._normalize_key(key)
        path = self._path_for_key(normalized, archived=archived)
        if not path.exists():
            return None
        return self._parse_schema_file(path, archived=archived)

    def create_schema(
        self,
        *,
        key: str,
        schema: dict[str, Any],
        label: str | None = None,
        description: str | None = None,
    ) -> dict[str, Any]:
        normalized = self._normalize_key(key)
        self._validate_label_schema(schema)
        active_path = self._path_for_key(normalized, archived=False)
        archived_path = self._path_for_key(normalized, archived=True)
        if active_path.exists():
            raise LabelSchemaRegistryError(f"Label schema '{normalized}' already exists")
        if archived_path.exists():
            raise LabelSchemaRegistryError(f"Label schema '{normalized}' exists in archive; restore it instead")

        active_path.write_text(
            self._render_payload(
                key=normalized,
                schema=schema,
                label=label,
                description=description,
            ),
            encoding="utf-8",
        )
        return self._parse_schema_file(active_path, archived=False)

    def update_schema(
        self,
        *,
        key: str,
        schema: dict[str, Any] | None = None,
        label: str | None = None,
        description: str | None = None,
    ) -> dict[str, Any]:
        normalized = self._normalize_key(key)
        active_path = self._path_for_key(normalized, archived=False)
        existing = self.get_schema(normalized, archived=False)
        if existing is None:
            raise LabelSchemaRegistryError(f"Label schema '{normalized}' not found")

        next_schema = dict(existing["schema"] if schema is None else schema)
        self._validate_label_schema(next_schema)
        next_label = str(existing.get("label", "") if label is None else label).strip()
        next_description = str(existing.get("description", "") if description is None else description).strip()
        active_path.write_text(
            self._render_payload(
                key=normalized,
                schema=next_schema,
                label=next_label,
                description=next_description,
            ),
            encoding="utf-8",
        )
        return self._parse_schema_file(active_path, archived=False)

    def archive_schema(self, key: str) -> dict[str, Any]:
        normalized = self._normalize_key(key)
        active_path = self._path_for_key(normalized, archived=False)
        archived_path = self._path_for_key(normalized, archived=True)
        if not active_path.exists():
            raise LabelSchemaRegistryError(f"Label schema '{normalized}' not found")
        if archived_path.exists():
            raise LabelSchemaRegistryError(f"Archive collision for label schema '{normalized}'")
        active_path.replace(archived_path)
        return self._parse_schema_file(archived_path, archived=True)

    def restore_schema(self, key: str) -> dict[str, Any]:
        normalized = self._normalize_key(key)
        active_path = self._path_for_key(normalized, archived=False)
        archived_path = self._path_for_key(normalized, archived=True)
        if not archived_path.exists():
            raise LabelSchemaRegistryError(f"Archived label schema '{normalized}' not found")
        if active_path.exists():
            raise LabelSchemaRegistryError(f"Label schema '{normalized}' already exists")
        archived_path.replace(active_path)
        return self._parse_schema_file(active_path, archived=False)

    def purge_schema(self, key: str) -> None:
        normalized = self._normalize_key(key)
        archived_path = self._path_for_key(normalized, archived=True)
        if not archived_path.exists():
            raise LabelSchemaRegistryError(f"Archived label schema '{normalized}' not found")
        archived_path.unlink()

    def _list_from_dir(self, base_dir: Path, *, archived: bool) -> list[dict[str, Any]]:
        records: list[dict[str, Any]] = []
        if not base_dir.exists():
            return records
        for path in sorted(base_dir.glob("*.json")):
            try:
                records.append(self._parse_schema_file(path, archived=archived))
            except LabelSchemaRegistryError:
                continue
        return records

    def _path_for_key(self, key: str, *, archived: bool) -> Path:
        base = self.archive_dir if archived else self.schema_dir
        return base / f"{key}.json"

    def _parse_schema_file(self, path: Path, *, archived: bool) -> dict[str, Any]:
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise LabelSchemaRegistryError(f"Invalid label schema file {path}: {exc}") from exc
        if not isinstance(payload, dict):
            raise LabelSchemaRegistryError(f"Invalid label schema file {path}: payload must be an object")

        schema = payload.get("schema")
        if not isinstance(schema, dict):
            raise LabelSchemaRegistryError(f"Invalid label schema file {path}: schema must be an object")
        self._validate_label_schema(schema)
        key = self._normalize_key(str(payload.get("key") or path.stem))
        stat = path.stat()
        return {
            "key": key,
            "label": str(payload.get("label") or self._default_label(key)).strip(),
            "description": str(payload.get("description") or "").strip(),
            "schema": schema,
            "preview": self._schema_preview(schema),
            "archived": archived,
            "source_path": path.relative_to(self.project_root).as_posix(),
            "updated_at": str(stat.st_mtime),
        }

    def _render_payload(
        self,
        *,
        key: str,
        schema: dict[str, Any],
        label: str | None,
        description: str | None,
    ) -> str:
        payload = {
            "doc": _GENERATED_DOC,
            "key": key,
            "label": str(label or "").strip() or self._default_label(key),
            "description": str(description or "").strip(),
            "schema": schema,
        }
        return f"{json.dumps(payload, ensure_ascii=False, indent=2)}\n"

    @staticmethod
    def _normalize_key(key: str) -> str:
        normalized = str(key or "").strip().lower()
        if not _KEY_PATTERN.fullmatch(normalized):
            raise LabelSchemaRegistryError(
                "Invalid schema key. Use 2-64 chars with lowercase letters, numbers, underscores, or hyphens; must start with a letter."
            )
        return normalized

    @staticmethod
    def _validate_label_schema(schema: dict[str, Any]) -> None:
        if not isinstance(schema, dict):
            raise LabelSchemaRegistryError("schema must be a JSON object")
        if schema.get("type") != "object":
            raise LabelSchemaRegistryError("label schema must be a top-level object schema")
        properties = schema.get("properties")
        if not isinstance(properties, dict):
            raise LabelSchemaRegistryError("label schema must define properties")
        spans = properties.get("spans")
        if not isinstance(spans, dict) or spans.get("type") != "array":
            raise LabelSchemaRegistryError("label schema must define a spans array")
        root_required = set(schema.get("required") or [])
        if "spans" not in root_required:
            raise LabelSchemaRegistryError("label schema must require the top-level spans field")
        items = spans.get("items")
        if not isinstance(items, dict) or items.get("type") != "object":
            raise LabelSchemaRegistryError("label schema spans items must be object schemas")
        span_properties = items.get("properties")
        if not isinstance(span_properties, dict):
            raise LabelSchemaRegistryError("label schema span items must define properties")
        required = set(items.get("required") or [])
        missing = {"label", "text", "start", "end"} - required
        if missing:
            raise LabelSchemaRegistryError(
                f"label schema span items must require: {', '.join(sorted(missing))}"
            )
        expected_types = {
            "label": "string",
            "text": "string",
            "start": "integer",
            "end": "integer",
        }
        for name, expected_type in expected_types.items():
            field_schema = span_properties.get(name)
            if not isinstance(field_schema, dict) or field_schema.get("type") != expected_type:
                raise LabelSchemaRegistryError(f"label schema field '{name}' must be type '{expected_type}'")

    @staticmethod
    def _default_label(key: str) -> str:
        return key.replace("-", " ").replace("_", " ").title()

    @staticmethod
    def _schema_preview(schema: dict[str, Any]) -> str:
        required = schema.get("required")
        if isinstance(required, list) and required:
            return f"Required: {', '.join(str(item) for item in required)}"
        return "Label JSON schema"
